version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install
  
  pre_build:
    commands:
      - echo "Running tests..."
      - npm test
      - echo "Build started on `date`"
  
  build:
    commands:
      - echo "Building application..."
      - npm run build
      - echo "Build completed on `date`"
  
  post_build:
    commands:
      - echo "Preparing deployment artifacts..."
      - echo "Build completed successfully!"

artifacts:
  files:
    - '**/*'
  name: BuildArtifact

cache:
  paths:
    - 'node_modules/**/*'